spring:
  profiles:
    active: @profiles.active@
  servlet:
    multipart:
      # 交给commons-fileupload处理
      enabled: false

server:
  port: 8088

#日志
logging:
  config: classpath:logback-spring.xml

uploader:
  file:
    domain: http://127.0.0.1:8088
    path: /var/uploader/files

